apiVersion: v1
kind: Namespace
metadata:
  name: hands-on
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-config
  namespace: hands-on
data:
  MY_MESSAGE: "Hello from ConfigMap 🚀"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-nginx
  namespace: hands-on
data:
  default.conf: |
    server {
      listen 8080;

      location = /ready {
        if (!-f /tmp/ready) { return 503; }
        return 200 'ready\n';
        add_header Content-Type text/plain;
      }

      location = /healthz {
        if (!-f /tmp/healthy) { return 500; }
        return 200 'ok\n';
        add_header Content-Type text/plain;
      }

      location / {
        root /usr/share/nginx/html;
        index index.html;
      }
    }

  index.html.template: |
    <!doctype html>
    <html>
      <head>
        <meta charset="utf-8">
        <title>hands-on</title>
      </head>
      <body style="font-family: Arial, sans-serif;">
        <h1>Hello world</h1>
        <p><b>MY_MESSAGE:</b> ${MY_MESSAGE}</p>
        <p><b>Pod:</b> ${HOSTNAME}</p>
      </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: hands-on
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 8080

          env:
            - name: MY_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: hello-config
                  key: MY_MESSAGE

          command: ["/bin/sh", "-c"]
          args:
            - |
              touch /tmp/ready /tmp/healthy;
              envsubst '$MY_MESSAGE $HOSTNAME' \
                < /etc/nginx/templates/index.html.template \
                > /usr/share/nginx/html/index.html;
              nginx -g 'daemon off;'

          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: nginx-templates
              mountPath: /etc/nginx/templates/index.html.template
              subPath: index.html.template

          resources:
            requests:
              cpu: "250m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "128Mi"

          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 3

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3

      volumes:
        - name: nginx-conf
          configMap:
            name: hello-nginx
            items:
              - key: default.conf
                path: default.conf

        - name: nginx-templates
          configMap:
            name: hello-nginx
            items:
              - key: index.html.template
                path: index.html.template
---
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: hands-on
spec:
  selector:
    app: hello
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
