apiVersion: v1
kind: Namespace
metadata:
  name: hands-on
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-config
  namespace: hands-on
data:
  MY_MESSAGE: "Hello from ConfigMap 🚀"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-nginx
  namespace: hands-on
data:
  default.conf: |
    server {
      listen 8080;

      location = /ready {
        if (!-f /tmp/ready) { return 503; }
        return 200 'ready\n';
        add_header Content-Type text/plain;
      }

      location = /healthz {
        if (!-f /tmp/healthy) { return 500; }
        return 200 'ok\n';
        add_header Content-Type text/plain;
      }

      location = /whoami {
        return 200 "$hostname\n";
        add_header Content-Type text/plain;
      }

      location / {
        root /usr/share/nginx/html;
        index index.html;
      }
    }
  index.html.template: |
    <!doctype html>
    <html>
      <head><meta charset="utf-8"><title>hands-on</title></head>
      <body style="font-family: Arial, sans-serif;">
        <h1>Hello world</h1>
        <p><b>MY_MESSAGE:</b> ${MY_MESSAGE}</p>
        <p><b>Pod:</b> ${HOSTNAME}</p>
        <p>Try: <code>/whoami</code>, <code>/ready</code>, <code>/healthz</code></p>
      </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: hands-on
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      volumes:
        - name: nginx-conf
          configMap:
            name: hello-nginx
            items:
              - key: default.conf
                path: default.conf
        - name: nginx-templates
          configMap:
            name: hello-nginx
            items:
              - key: index.html.template
                path: index.html.template
        - name: shared
          emptyDir: {}

      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 8080

          env:
            - name: MY_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: hello-config
                  key: MY_MESSAGE

          command: ["/bin/sh", "-c"]
          args:
            - |
              touch /tmp/ready /tmp/healthy;
              envsubst '$MY_MESSAGE $HOSTNAME' \
                < /etc/nginx/templates/index.html.template \
                > /usr/share/nginx/html/index.html;
              nginx -g 'daemon off;'

          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: nginx-templates
              mountPath: /etc/nginx/templates/index.html.template
              subPath: index.html.template
            - name: shared
              mountPath: /shared

          # small app footprint
          resources:
            requests:
              # CPU is measured in millicores (m).
              # 1000m = 1 full vCPU core
              # 500m  = 0.5 vCPU (half a core)
              # 100m  = 0.1 vCPU
              cpu: "100m"
              # Memory is measured in Mebibytes (Mi).
              # Mi uses base 2 (2^20 bytes).
              # 1 Mi = 1,048,576 bytes
              # 512Mi ≈ 0.5 GiB
              memory: "64Mi"
            limits:
              # The maximum CPU the container is allowed to use.
              # If it tries to exceed this, it will be throttled.
              cpu: "200m"
              # The maximum memory the container may use.
              # If it exceeds this, it will be OOM-killed.
              memory: "128Mi"

          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 3

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3

        - name: cpu-burn
          image: busybox:1.36
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "cpu-burn sidecar ready. toggle with: touch /shared/burn";
              while true; do
                if [ -f /shared/burn ]; then
                  # Safe CPU burn: tight loop (no forks)
                  while [ -f /shared/burn ]; do :; done
                else
                  sleep 1
                fi
              done
          volumeMounts:
            - name: shared
              mountPath: /shared
          # This is what makes HPA + CA visible/reliable:
          # 1 vCPU requested per pod when scaled up
          resources:
            requests:
              cpu: "1000m"
              memory: "16Mi"
            limits:
              cpu: "1000m"
              memory: "32Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: hands-on
spec:
  selector:
    app: hello
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hello-hpa
  namespace: hands-on
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello
  minReplicas: 1
  maxReplicas: 12
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
